### PR TITLE
[Fix] Error.captureStackTrace issue

### PR DESCRIPTION
**Pull request by ruslan-polutsygan**
Call parent constructor before `Error.captureStackTrace`

### CODE REVIEW

**Comment by SebastienElet** [comment]
@ruslan-polutsygan Thanks, could you update the `engines` in `package.json` & `travis.yml` please ?

**Comment by ruslan-polutsygan** [comment]
@SebastienElet package.json and travis.yml updated

**Comment by nfroidure** [comment]
Looks like you forgot this PR ;) https://github.com/SimpliField/yhttperror/pull/11

**Comment by SebastienElet** [comment]
@nfroidure outch

**Pull request closed without merging**
